### ISSUE TITLE
404 when trying to GET aurelia-cli-electron-app/source/main.js

### ISSUE THREAD

**Issue by javiercbk** [MeirionHughes/aurelia-cli-electron-app#2]
It seems that the application is trying to get _source/main.js_ when clearly it does not exist.

This happens when an _aurelia-app_ attribute value is given, particularly in _index.html_

``` html
<body aurelia-app="main">
  <script src="output/vendor-bundle.js" data-main="aurelia-bootstrapper"></script>
</body>
```

If I remove `="main"` it will search for _app.js_ instead.

**Comment by MeirionHughes** [comment]
are you running it on linux or mac? main.js does exist in the app bundle.  I don't have any exceptions myself, although there was an unclosed element. 

![untitled](https://cloud.githubusercontent.com/assets/3584509/19360847/20bcdd26-9178-11e6-8c27-436102a300d2.png)

**Comment by javiercbk** [comment]
I'm running on mac OS X Sierra.

Also my app-bundle.js is empty. There must be an issue when generating that file and it's causing this mess

**Comment by javiercbk** [comment]
After the latest commit it is fixed. Thanks!

**Comment by MeirionHughes** [comment]
cool; I believe there is an issue with back-slashes on non-windows. repo is bit of a testing ground at the moment. :D
