### ISSUE TITLE
Using nodejs core modules

### ISSUE THREAD

**Issue by gbouteiller** [MeirionHughes/aurelia-cli-electron-app#5]
Hi,
First of all, thank you for your work. I have a problem trying to use nodejs child_process in the skeleton as aurelia-cli fails to run. The CLI is looking for a child_process.js file. I've been able to fix it by adapting your fix for electron in order to load child_process from nodeRequire but I'm looking to a more robust solution as it would mean to do it for each nodejs module. Do you have a clue?

**Comment by MeirionHughes** [comment]
I think the more robust solution is to get the module loader (require.js) to fallback to the `node-require` whenever it doesn't know about a (non-relative) module. I don't know how to go about doing that though. 

you could posibly avoid using the import style and use the saved `nodeRequire` directly: 

`const remote:Electron.Remote = (<any>window).nodeRequire("electron").remote;`

**Comment by fgambino** [comment]
I'm not sure how to get the loader to fallback to node's `require()`, but I've been doing this to support the core modules: 

**aurelia_project/aurelia.json**
```
{
  "name": "fs",
  "path": "../aurelia_project/native/fs"
}
```

**aurelia_project/native/fs.js**
```
define('fs', function() { return window.nodeRequire('fs'); });
```

One entry/file per module. I do the same for electron.js.
